apiVersion: v1
kind: Pod
metadata:
  labels:
    gophercon.turkiye/available: "true"
  name: alpine-valid
spec:
  containers:
  - command: ["/bin/sh"]
    args:
    - "-c"
    - "sleep 600"
    image: alpine
    name: alpine
